# Generated by Django 5.2.1 on 2025-05-31 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Construction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rus_tili', models.CharField(max_length=150)),
                ('uzbek_kiril', models.CharField(max_length=150)),
                ('uzbek_lotin', models.CharField(max_length=150)),
                ('ingliz_tili', models.CharField(max_length=150)),
                ('turk_tili', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'construction',
                'ordering': ['uzbek_lotin'],
            },
        ),
    ]
